### ISSUE TITLE
feat: EKS image

### ISSUE THREAD

**Issue by scottd018** [klearwave/node#2]
Create the following to produce a working node image to be run as an Amazon AMI for EKS:

- [ ] Based on Talos Linux with custom image workflow > https://www.talos.dev/v1.9/advanced/building-images/
- [ ] Both ARM/AMD architectures
- [ ] Create Make targets that describe the process
- [ ] Create README to describe the process
- [ ] [https://developer.hashicorp.com/packer/integrations/hashicorp/amazon](Packer) to build the image with `make aws` target
- [ ] GitHub actions CI/CD workflow to build and push the image when a new tag is pushed

Acceptance critera:

- [ ] Must work in Kubernetes using `eksctl create cluster -f cluster-config.yaml` with the following cluster config:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-west-2
  version: "1.27"

nodeGroups:
  - name: custom-nodes
    instanceType: t3.medium
    ami: "ami-0abcd1234efgh5678"  # Replace with your custom AMI ID
    minSize: 2
    maxSize: 5
    desiredCapacity: 3
    ssh:
      allow: true  # Enable SSH access if needed
```

Sample code to do this:

- https://github.com/aws-samples/amazon-eks-custom-amis
- https://github.com/awslabs/amazon-eks-ami
- https://repost.aws/knowledge-center/eks-custom-linux-ami
- Requirements > https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html
